DROP TABLE IF EXISTS lobby;
CREATE TABLE lobby (
    id VARCHAR(36) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS player;
CREATE TABLE player (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS lobby_player;
CREATE TABLE lobby_player (
    id VARCHAR(36) PRIMARY KEY,
    lobby_id VARCHAR(36) NOT NULL,
    player_id VARCHAR(36) NOT NULL
);